version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src/database:/app/src/database
    environment:
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key}
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/profile"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

