version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    volumes:
      - ./src/database:/app/src/database
    environment:
      - FLASK_ENV=production

  nodejs:
    build:
      context: ./payment_server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - FRONTEND_URL=${FRONTEND_URL}