version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - SECRET_KEY=${SECRET_KEY:-default-secret-key}
      - PAYMENT_SERVER_URL=${PAYMENT_SERVER_URL:-https://3000-iueh88sebpgtsvwl1znd6-b52cfc53.manusvm.computer}
      - DATABASE_PATH=/app/src/database/app.db
      - SITE_URL=${SITE_URL:-http://localhost:5000}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5000}
    volumes:
      - ./src/database:/app/src/database
      - ./src/static/uploads:/app/src/static/uploads
    restart: unless-stopped

# NOTA: O payment server agora está hospedado externamente na Manus
# URL: https://3000-iueh88sebpgtsvwl1znd6-b52cfc53.manusvm.computer

